### ISSUE TITLE
CameraExt::get_gv_packet_size returns Result<(), …> instead of Result<usize, …>

### ISSUE THREAD

**Issue by Ekleog** [robohouse-delft/aravis-rs#1]
Everything is in the title. See also:
-  https://docs.rs/aravis/0.0.2/aravis/trait.CameraExt.html#tymethod.gv_get_packet_size
- https://aravisproject.github.io/docs/aravis-0.7/ArvCamera.html#arv-camera-gv-get-packet-size

**Comment by Ekleog** [comment]
Actually, the same issue is also present with CameraExt::get_payload:
- https://docs.rs/aravis/0.0.2/aravis/trait.CameraExt.html#tymethod.get_payload
- https://aravisproject.github.io/docs/aravis-0.7/ArvCamera.html#arv-camera-get-payload

**Comment by de-vri-es** [comment]
Ah thanks for reporting it. This probably goes for all fallible functions that return an integer. My guess is it's similar to https://github.com/AravisProject/aravis/issues/315. We'll probably have to work with upstream to get alternate signatures. But I should dig a bit deeper before jumping to conclusions :)

If you have a pressing need, you can work around it for now using the `aravis-sys` crate to call the raw C function.

**Comment by Ekleog** [comment]
Thank you for your feedback! I will try using the `aravis-sys` crate in the meantime :)

**Comment by Ekleog** [comment]
Hmm… looking more into it, I can't find a way to use the `aravis-sys` crate directly, as I can't find in `aravis` a way to switch between an `aravis::Camera` and an `aravis_sys::ArvCamera`. So, unless I miss something introduced by gtk-rs (which I must say I don't get all the inner workings), I don't think this workaround would work as is?

**Comment by de-vri-es** [comment]
Sorry for the late reply. It should be possible to convert a `aravis::Camera` to `*mut aravis_sys::ArvCamera` using the [`glib::translate::ToGlibPtrMut`](https://docs.rs/glib/0.9.3/glib/translate/trait.ToGlibPtrMut.html) trait.

Once you have that you should be able to call `aravis_sys` functions on it.

Let me know if you run into issues :)

**Comment by de-vri-es** [comment]
I submitted a PR to support functions like this in gtk-rs/gir: https://github.com/gtk-rs/gir/pull/891. I hope they agree to solve it there. I also think I have a full list of affected functions.

**Comment by de-vri-es** [comment]
I already ran the patched tool to regenerate the `aravis` crate. So the master branch should have fixed functions now.

Thanks again for the report, and please let us know if you find any other errors in the API :)

**Comment by de-vri-es** [comment]
The PR was accepted. Wooh :tada:

**Comment by Ekleog** [comment]
Great, thank you! :tada: Do you plan on releasing a 0.0.3 soon, or should I just keep the pin on c310df778d75cec90b83bafcd56b535094fd6ce8 I have for now? :)

**Comment by de-vri-es** [comment]
Just released 0.0.3 :rocket:  :)

**Comment by Ekleog** [comment]
Great, thank you!
