### ISSUE TITLE
Failed to set trigger source to software: AcquisitionFrameRateEnable

### ISSUE THREAD

**Issue by osiler** [robohouse-delft/aravis-rs#13]
Hi,

Thanks for this set of crates, I have been working with your examples in the aravis-utils directory but am unable to run a test capture.

```bash
aravis-capture -c 10 --save test_images/ X.X.X.X
Connecting to camera X.X.X.X
Connected.
** (process:XXXX): CRITICAL **: 12:06:07.509: arv_gc_feature_node_is_available: assertion 'error == NULL || *error == NULL' failed
Error: Failed to set trigger source to software: [AcquisitionFrameRateEnable] [RegAcquisitionFrameRateEnable] GigEVision write_memory error (write-protect).
```

This feature is available on the camera, however I think it might be related to [this](https://github.com/AravisProject/aravis/pull/769), with patches for specific cameras [here](https://github.com/AravisProject/aravis/blob/9756369873efface7477ecc6e65907433089348a/src/arvcamera.c#L1283).

I am new to the FFI - C interopt world so i am unsure how could I use the [binding](https://github.com/robohouse-delft/aravis-rs/blob/bcd2d2223812f30b233ffdd6a693cd487f1098f4/aravis-sys/src/lib.rs#L2934) in aravis-sys to accomplish a similar bit of logic as seen in the arivis function for specific camera quirks? In addition I was unable to find a wrapper for the [arv_camera_set_frame_rate_enable](https://github.com/AravisProject/aravis/blob/9756369873efface7477ecc6e65907433089348a/src/arvcamera.c#L1273), which I could potentially call prior to setting other camera features which may negate the error.

EDIT: Apologies, the patch is only two weeks old in main so unlikely to be in your 0.8.22 FFI binding is there a help file / readme that can point me in the direction of bumping this crate to a dev branch and trying out the patch in main?

**Comment by hgaiser** [comment]
My colleague worked on this mostly, but he's on sabbatical at the moment so he won't be able to help ;). I can maybe help, but my knowledge about this crate is limited. I know that the procedure of updating the bindings is convoluted, and that there's no documentation as of yet unfortunately. The best I can do is direct you to [this](https://gtk-rs.org/gir/book/) book.

However I'm not sure that will solve your problem. It seems that Aravis is setting [`AcquisitionFrameRateEnable`](https://github.com/AravisProject/aravis/blob/main/src/arvcamera.c#L1352-L1353), which is a write-protected setting in your case. Can you try a similar example with Aravis directly? I'd be surprised if you don't get an error there (make sure it is calling `arv_camera_set_trigger`).

**Comment by osiler** [comment]
Great thanks for the links. Yes from first pass it looks like it is write protected however the documentation specified that the value has read, write access. The other aspect that may be causing this issue is a parent / child relationship that is enforcing the read write access, like exposure. I will try with the aravis API and see how I go. 

In terms of the gir  documentation what would be the best way to start given that your colleague is on sabbatical, it would be great to get to a point where this set of crates can track aravis in a dev branch.

**Comment by hgaiser** [comment]
> Great thanks for the links. Yes from first pass it looks like it is write protected however the documentation specified that the value has read, write access. The other aspect that may be causing this issue is a parent / child relationship that is enforcing the read write access, like exposure. I will try with the aravis API and see how I go.

Is it possible the documentation is wrong? Using Aravis directly is the best way to verify if the problem is resolved upstream. If it works on the `main` branch, please also try it on `0.8.22` as that is what we created the bindings for.

> In terms of the gir documentation what would be the best way to start given that your colleague is on sabbatical, it would be great to get to a point where this set of crates can track aravis in a dev branch.

You mean in a way that this crate automatically builds the bindings for upstream aravis? I believe there was quite some manual labor involved, as the generated bindings had some flaws. I don't know the details for this I'm afraid..

**Comment by osiler** [comment]
As highlighted in [post](https://github.com/AravisProject/aravis/issues/778#issuecomment-1575316150) write permission errors can be encountered for some manufacturers. I had to include the device reset commands in the camera initialisation in the capture example.
