### ISSUE TITLE
Aravis 0.8.5

### ISSUE THREAD

**Issue by lovesegfault** [robohouse-delft/aravis-rs#6]
We're behind upstream by a couple releases, maybe a new version of the crate is warranted?

Thanks!

**Comment by de-vri-es** [comment]
Thanks for the reminder :)

Updated to Aravis 0.8.5 and released as 0.6.0. If everything went right, it should still be compatible with Aravis 0.8.x. There's a new feature (auto-generated by the gir tool) to enable new interfaces from 0.8.3.

I also used a newer `gtk-rs/gir` version, which has generated different constructors (no more `new_from_*` but just `from_*`). However, the 0.6.0 bump should already indicate that it is backwards incompatible.

If you run into problems with the new bindings, please let me know so it can be fixed :)

Thanks again!

**Comment by lovesegfault** [comment]
Thank you Maarten!
